package db2struct

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"time"
	"unicode"
)

const (
	PrefixModel string = "Model"
	PrefixLogic string = ""
	PrefixDTO   string = "DTO"
)

var mapping map[string]map[string]string = map[string]map[string]string{
	PrefixModel: map[string]string{
		golangByteArray:  "[]byte",
		gureguNullInt:    "null.Int",
		sqlNullInt:       "sql.NullInt64",
		sqlNullInt64:     "sql.NullInt64",
		golangInt:        "int",
		golangInt64:      "int64",
		gureguNullFloat:  "null.Float",
		sqlNullFloat:     "sql.NullFloat64",
		golangFloat:      "float",
		golangFloat32:    "float32",
		golangFloat64:    "float64",
		gureguNullString: "null.String",
		sqlNullString:    "sql.NullString",
		gureguNullTime:   "null.Time",
		golangTime:       "time.Time",
	},
	PrefixDTO: map[string]string{
		golangByteArray:  "[]byte",
		gureguNullInt:    "*json.Number",
		sqlNullInt:       "*json.Number",
		sqlNullInt64:     "*json.Number",
		golangInt:        "json.Number",
		golangInt64:      "json.Number",
		gureguNullFloat:  "*json.Number",
		sqlNullFloat:     "*json.Number",
		golangFloat:      "json.Number",
		golangFloat32:    "json.Number",
		golangFloat64:    "json.Number",
		gureguNullString: "*string",
		sqlNullString:    "*string",
		gureguNullTime:   "*time.Time",
		golangTime:       "time.Time",
	},
	PrefixLogic: map[string]string{
		golangByteArray:  "[]byte",
		gureguNullInt:    "int",
		sqlNullInt:       "int",
		sqlNullInt64:     "int64",
		golangInt:        "int",
		golangInt64:      "uint64",
		gureguNullFloat:  "float64",
		sqlNullFloat:     "float64",
		golangFloat:      "float",
		golangFloat32:    "float32",
		golangFloat64:    "float64",
		gureguNullString: "string",
		sqlNullString:    "string",
		gureguNullTime:   "*time.Time",
		golangTime:       "time.Time",
	},
}

// Constants for return types of golang
const (
	golangByteArray  = "[]byte"
	gureguNullInt    = "null.Int"
	sqlNullInt       = "sql.NullInt"
	sqlNullInt64     = "sql.NullInt64"
	golangInt        = "int"
	golangInt64      = "int64"
	gureguNullFloat  = "null.Float"
	sqlNullFloat     = "sql.NullFloat64"
	golangFloat      = "float"
	golangFloat32    = "float32"
	golangFloat64    = "float64"
	gureguNullString = "null.String"
	sqlNullString    = "sql.NullString"
	gureguNullTime   = "null.Time"
	golangTime       = "time.Time"
)

// commonInitialisms is a set of common initialisms.
// Only add entries that are highly unlikely to be non-initialisms.
// For instance, "ID" is fine (Freudian code is rare), but "AND" is not.
var commonInitialisms = map[string]bool{
	"API":   true,
	"ASCII": true,
	"CPU":   true,
	"CSS":   true,
	"DNS":   true,
	"EOF":   true,
	"GUID":  true,
	"HTML":  true,
	"HTTP":  true,
	"HTTPS": true,
	"ID":    true,
	"IP":    true,
	"JSON":  true,
	"LHS":   true,
	"QPS":   true,
	"RAM":   true,
	"RHS":   true,
	"RPC":   true,
	"SLA":   true,
	"SMTP":  true,
	"SSH":   true,
	"TLS":   true,
	"TTL":   true,
	"UI":    true,
	"UID":   true,
	"UUID":  true,
	"URI":   true,
	"URL":   true,
	"UTF8":  true,
	"VM":    true,
	"XML":   true,
}

var intToWordMap = []string{
	"zero",
	"one",
	"two",
	"three",
	"four",
	"five",
	"six",
	"seven",
	"eight",
	"nine",
}

//Debug level logging
var Debug = false

// Generate Given a Column map with datatypes and a name structName,
// attempts to generate a struct definition
func Generate(columnTypes map[string]map[string]string, tableName string, structName string, pkgName string, jsonAnnotation bool, gormAnnotation bool, gureguTypes bool, structType string) ([]byte, error) {
	var dbTypes string
	name := structName + structType
	dbTypes, from, to := generateMysqlTypes(columnTypes, 0, jsonAnnotation, gormAnnotation, gureguTypes, structType)
	src := fmt.Sprintf("%s\npackage %s\ntype %s %s}",
		fmt.Sprintf("/// IMPORTANT:Auto Generate From https://github.com/imiskolee/db2struct\n/// Generated By:%s",
			time.Now().String()),
		pkgName,
		name,
		dbTypes)
	if gormAnnotation == true {
		tableNameFunc := "// IMPORTANT:Auto Generate\n" +
			"func (*" + name + ") TableName() string {\n" +
			"	return \"" + tableName + "\"" +
			"}"
		src = fmt.Sprintf("%s\n%s", src, tableNameFunc)
	}

	prefix := ""

	switch structType {
	case PrefixModel:
		prefix = ""
	case PrefixLogic:
		prefix = PrefixDTO
	}

	if from != "" {
		f := "// IMPORTANT:Auto Generate\n" + "func(s *" + name + ") From" + prefix + "(t *" + (structName) + prefix + ") error {\n" + from + "\n" + "return nil\n}"
		src = fmt.Sprintf("%s\n%s", src, f)
	}

	if to != "" {
		f := "// IMPORTANT:Auto Generate\n" + "func(s *" + name + ") To" + prefix + "(t *" + (structName) + prefix + ") error {\n" + to + "\n" + "return nil\n}"
		src = fmt.Sprintf("%s\n%s", src, f)
	}

	if gormAnnotation == true {

		{
			f := "// IMPORTANT:Auto Generate\n" + "func(m *" + (name) + ") Valid() error {\n" +
				"return errors.New(\"please valid you request\") \n}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}

		{
			f := "// IMPORTANT:Auto Generate\n" + "func (m*" + name + ") BeforeCreate(scope *gorm.Scope) error {\n" +
				"  if err := m.Valid(); err != nil {\n" +
				"    return err\n}\nreturn nil\n" +
				"}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{

			f := "// IMPORTANT:Auto Generate\n" + "func (m*" + name + ") BeforeUpdate(scope *gorm.Scope) error {\n" +
				"  if err := m.Valid(); err != nil {\n" +
				"    return err\n}\nreturn nil\n" +
				"}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{
			f := "// IMPORTANT:Auto Generate\n" + "func (m*" + name + ") BeforeSave(scope *gorm.Scope) error {\n" +
				"  if err := m.Valid(); err != nil {\n" +
				"    return err\n}\nreturn nil\n" +
				"}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}

		//AutoCreate
		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "Create(model *" + name + ") store.StoreChannel {\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := gormInstance.Create(model).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"  ch.SendData(model)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}

		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "Update(model *" + name + ") store.StoreChannel {\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := gormInstance.Update(model).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"ch.SendData(model)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "UpdateWithFields(model *" + name + ",fields ...string) store.StoreChannel {\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := model.Valid(); err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"}\n" +
				"    if err := gormInstance.Model(&" + (name) + "{}).Select(fields).Update(model).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"ch.SendData(model)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "DeleteByID(id int) store.StoreChannel {\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := gormInstance.Model(&" + (name) + "{}).Where(\"id=?\",id).Delete(&" + (name) + "{}).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"ch.SendData(nil)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "GetRowByID(id int) store.StoreChannel {\n" +
				"  record := new(" + name + ")\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := gormInstance.Model(&" + (name) + "{}).Where(\"id=?\",id).First(&record).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"ch.SendData(record)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "GetListByPagination(p *pagination.DSL) store.StoreChannel {\n" +
				"  var records []" + name + "\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := gormInstance.Model(&" + (name) + "{}).Where(\"1\").Scopes(gorm_scopes.ScopeTableDSL(p)).Find(&records).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"ch.SendData(records)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
		{
			f := "// IMPORTANT:Auto Generate\n" + "func " + structName + "GetCountByPagination(p *pagination.DSL) store.StoreChannel {\n" +
				"  var count int64\n" +
				"  ch := make(store.StoreChannel)\n" +
				"  go func(){\n" +
				"    if err := gormInstance.Model(&" + (name) + "{}).Where(\"1\").Scopes(gorm_scopes.ScopeTableDSL(p)).Count(&count).Error; err != nil {\n" +
				"      ch.SendError(err)\n" +
				"      return\n" +
				"    }\n" +
				"ch.SendData(count)\n" +
				"  }()\n" +
				"return ch\n" + "}"
			src = fmt.Sprintf("%s\n%s", src, f)
		}
	}

	formatted, err := format.Source([]byte(src))
	if err != nil {
		err = fmt.Errorf("error formatting: %s, was formatting\n%s", err, src)
	}
	return formatted, err
}

// fmtFieldName formats a string as a struct key
//
// Example:
// 	fmtFieldName("foo_id")
// Output: FooID
func fmtFieldName(s string) string {
	name := lintFieldName(s)
	runes := []rune(name)
	for i, c := range runes {
		ok := unicode.IsLetter(c) || unicode.IsDigit(c)
		if i == 0 {
			ok = unicode.IsLetter(c)
		}
		if !ok {
			runes[i] = '_'
		}
	}
	return string(runes)
}

func lintFieldName(name string) string {
	// Fast path for simple cases: "_" and all lowercase.
	if name == "_" {
		return name
	}

	for len(name) > 0 && name[0] == '_' {
		name = name[1:]
	}

	allLower := true
	for _, r := range name {
		if !unicode.IsLower(r) {
			allLower = false
			break
		}
	}
	if allLower {
		runes := []rune(name)
		if u := strings.ToUpper(name); commonInitialisms[u] {
			copy(runes[0:], []rune(u))
		} else {
			runes[0] = unicode.ToUpper(runes[0])
		}
		return string(runes)
	}

	// Split camelCase at any lower->upper transition, and split on underscores.
	// Check each word for common initialisms.
	runes := []rune(name)
	w, i := 0, 0 // index of start of word, scan
	for i+1 <= len(runes) {
		eow := false // whether we hit the end of a word

		if i+1 == len(runes) {
			eow = true
		} else if runes[i+1] == '_' {
			// underscore; shift the remainder forward over any run of underscores
			eow = true
			n := 1
			for i+n+1 < len(runes) && runes[i+n+1] == '_' {
				n++
			}

			// Leave at most one underscore if the underscore is between two digits
			if i+n+1 < len(runes) && unicode.IsDigit(runes[i]) && unicode.IsDigit(runes[i+n+1]) {
				n--
			}

			copy(runes[i+1:], runes[i+n+1:])
			runes = runes[:len(runes)-n]
		} else if unicode.IsLower(runes[i]) && !unicode.IsLower(runes[i+1]) {
			// lower->non-lower
			eow = true
		}
		i++
		if !eow {
			continue
		}

		// [w,i) is a word.
		word := string(runes[w:i])
		if u := strings.ToUpper(word); commonInitialisms[u] {
			// All the common initialisms are ASCII,
			// so we can replace the bytes exactly.
			copy(runes[w:], []rune(u))

		} else if strings.ToLower(word) == word {
			// already all lowercase, and not the first word, so uppercase the first character.
			runes[w] = unicode.ToUpper(runes[w])
		}
		w = i
	}
	return string(runes)
}

// convert first character ints to strings
func stringifyFirstChar(str string) string {
	first := str[:1]

	i, err := strconv.ParseInt(first, 10, 8)

	if err != nil {
		return str
	}

	return intToWordMap[i] + "_" + str[1:]
}
